### PR TITLE
Port functionality to FFMPEG for Linux

### PR DESCRIPTION
**Pull request by cyrus01337**

### CODE REVIEW

**Comment by JDJGInc** [comment]
@cyrus01337 just saw this now, what status would say this would be?

**Comment by cyrus01337** [comment]
Ready to merge

**Comment by JDJGInc** [comment]
Fails to work with my configuration.
Are you sure?

**Comment by cyrus01337** [comment]
Tested it on a system configured to run it already.

**Comment by JDJGInc** [comment]
Lastest script and everything else.

**Comment by cyrus01337** [comment]
Sounds good, looks fine to merge.

**Comment by JDJGInc** [comment]
I am sorry but it does not work for me
I cannot accept the pr for rn.

**Comment by JDJG3493** [comment]
> Sounds good, looks fine to merge.

I appreciated this pr but trying to forcibly close it on me when i showed you what did not work.
I wanted to make sure it worked for myself you could have shown me something of it working.
or bring up your issue with this rather than blocking me.
Instead you passive aggressively got angry at me and then blocked me.

You could have talked to me about it.

**Comment by JDJG3493** [comment]
@cyrus01337 I am sorry if I didn't get the hint to let you be for a bit but please tell me if I am frustrating you.

**Pull request closed without merging**
